# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
dist: trusty
cache: packages
fortran: false

os:
  - linux
  - osx

r:
  - oldrel
  - release

after_success:
  - Rscript -e 'covr::codecov()'
